#!/usr/bin/env bash

# get some project-wide vars
srcdir=$(dirname "$(stat -f "$0")")
source "${srcdir}"/vars.sh

temp=$TMPDIR$(uuidgen)

# download the app
printf "downloading vanilla google chrome...\n"
mkdir -p "${temp}/mount"
curl https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg > "${temp}/1.dmg"
printf "done\n\n"

# install the app
printf "installing vanilla google chrome...\n"
yes | hdiutil attach -noverify -nobrowse -mountpoint "${temp}/mount" "${temp}/1.dmg" > /dev/null 2>&1
cp -r "$temp"/mount/*.app "/Applications/${appname}.app"
hdiutil detach "${temp}/mount" > /dev/null 2>&1
rm -r "${temp}"
printf "done\n\n"

# change the icon
printf "changing app iconn from chrome to jupyter...\n"
cp "${srcdir}/app.icns" "/Applications/${appname}.app/Contents/Resources/app.icns"
printf "done\n\n"

# rename the chrome exe
printf "renaming chrome executable...\n"
mv "/Applications/${appname}.app/Contents/MacOS/Google Chrome" "/Applications/${appname}.app/Contents/MacOS/jupyter_chrome_exe"
printf "done\n\n"

printf "copying executable scripts over to app...\n"

# copy the script that'll be the actual exe to the app
cp "${srcdir}/${appname}" "/Applications/${appname}.app/Contents/MacOS/"

# copy some support scripts
cp "${srcdir}/vars.sh" "/Applications/${appname}.app/Contents/MacOS/"
cp "${srcdir}/${appname}_exe_script" "/Applications/${appname}.app/Contents/MacOS/"

printf "done\n\n"

# modify the app's plist's exe to point to the script we just copied over
printf "Modifying app's Info.plist to point to executable scripts...\n"
plutil -replace CFBundleExecutable -string "${appname}" "/Applications/${appname}.app/Contents/Info.plist"
printf "done\n\n"
