#!/usr/bin/env bash

# get some project-wide vars
srcdir=$(dirname "$(stat -f "$0")")
source "${srcdir}"/vars.sh

# create the user-data-dir, if necessary
mkdir -p ${jchromeuserdir}

# start up a new instance of chrome with the appropriate user-data-dir
"/Applications/${appname}.app/Contents/MacOS/jupyter_chrome_exe" --user-data-dir="${jchromeuserdir}" "$@" > /dev/null 2>&1
