#!/usr/bin/env bash

# get some project-wide vars
srcdir=$(dirname "$(stat -f "$0")")
source "${srcdir}"/vars.sh

# start up a jupyter notebook kernel-thing in a new iterm window
osascript -e 'activate application "iTerm"'
osascript -e 'tell application "System Events" to keystroke "n" using command down'
osascript -e 'tell application "iTerm" to tell current session of current window to write text "jupyter notebook --browser=\"/Applications/jupyter_chrome.app/Contents/MacOS/jupyter_chrome_exe_script --new-window %s\""'
