#!/usr/bin/env bash
srcdir=$(dirname "$(stat -f "$0")")

# get some project-wide vars
source "${srcdir}"/vars.sh

jchromeuserdir="${HOME}/Library/Application Support/${appname}"

# start up a new instance of chrome with the appropriate user-data-dir
"/Applications/${appname}.app/Contents/MacOS/jupyter_chrome_exe" --user-data-dir=${jchromeuserdir} "$@" > /dev/null 2>&1
